# Generated by Django 4.1.13 on 2024-03-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bloc', models.CharField(max_length=32)),
                ('nombre_sall', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProduitMedicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=32)),
                ('date_enreg', models.DateTimeField()),
                ('date_exp', models.DateTimeField()),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RessourcesMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=32, null=True)),
                ('quantite', models.IntegerField()),
                ('description', models.TextField()),
                ('date_enreg', models.DateTimeField()),
                ('service_materiel', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sall', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('num_bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.bloc')),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lit', models.IntegerField()),
                ('statut_lit', models.BooleanField(default=False, null=True)),
                ('num_sall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.salle')),
            ],
        ),
    ]
