# Generated by Django 4.1.1 on 2024-05-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitmedicaux',
            name='date_enreg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
