# Generated by Django 4.1.1 on 2024-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitmedicaux',
            name='prix',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
