# Generated by Django 4.1.1 on 2024-04-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0002_produitmedicaux_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitmedicaux',
            old_name='prix',
            new_name='prix_unitaire',
        ),
    ]
