# Generated by Django 4.1.1 on 2024-05-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ressources', '0002_alter_produitmedicaux_date_enreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitmedicaux',
            name='date_exp',
            field=models.DateField(),
        ),
    ]
