# Generated by Django 4.1.13 on 2024-03-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emeteur', models.CharField(max_length=128)),
                ('recepteur', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('date_envoie', models.DateTimeField()),
            ],
        ),
    ]
