# Generated by Django 4.1.13 on 2024-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='date_envoie',
        ),
        migrations.AddField(
            model_name='chat',
            name='date_envoi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
