# Generated by Django 4.1.13 on 2024-03-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fonction', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=9)),
                ('tel', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('identifiant', models.CharField(max_length=32)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField()),
                ('heure_rdv', models.TimeField()),
                ('sujet_rdv', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_conge', models.DateTimeField()),
                ('fin_conge', models.DateTimeField()),
                ('motif', models.TextField()),
                ('status_conge', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('horaire', models.TimeField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
    ]
