# Generated by Django 4.1.13 on 2024-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0002_fonction_personnel_service_rendezvous_conge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='identifiant',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
