# Generated by Django 4.1.13 on 2024-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0003_alter_personnel_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, upload_to='profil_personnel/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_service/'),
        ),
    ]
