# Generated by Django 4.1.1 on 2024-03-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0004_personnel_image_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rendezvous',
        ),
    ]
