# Generated by Django 4.1.1 on 2024-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0007_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
