# Generated by Django 4.1.1 on 2024-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0008_utilisateur_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='identifiant',
            field=models.CharField(max_length=30),
        ),
    ]
