# Generated by Django 4.1.1 on 2024-04-24 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0009_remove_personnel_is_active_remove_personnel_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
