# Generated by Django 4.1.1 on 2024-05-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personnel_Service', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ressources', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=9)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=32)),
                ('profil_patient', models.ImageField(blank=True, upload_to='profil_patient/')),
                ('adresse', models.CharField(max_length=30)),
                ('identifiant', models.CharField(max_length=30)),
                ('date_enrgistrement', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_analyse', models.CharField(max_length=32)),
                ('dure_analyse', models.TimeField()),
                ('prix_analyse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('sujet_rdv', models.TextField(blank=True, null=True)),
                ('status_rdv', models.CharField(choices=[('confirmé', 'confirmé'), ('en attente', 'en attente'), ('annulé', 'annulé')], default='en attente', max_length=32)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=128)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('num_lit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.lit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.service')),
            ],
        ),
        migrations.CreateModel(
            name='FactureSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(max_length=32)),
                ('montant', models.IntegerField()),
                ('date_facture', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='FactureProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_factureproduit', models.DateTimeField()),
                ('montant', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_examen', models.CharField(max_length=128)),
                ('date_examen', models.DateTimeField(auto_now=True)),
                ('tarif', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('laborantain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.typeanalyse')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.CharField(max_length=128)),
                ('antecedant', models.CharField(max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poid', models.CharField(max_length=4)),
                ('temperature', models.CharField(max_length=4)),
                ('tension', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=4)),
                ('taille', models.CharField(max_length=4)),
                ('plainte', models.TextField()),
                ('diagnostic', models.TextField()),
                ('prescription', models.CharField(max_length=128)),
                ('date_consultation', models.DateTimeField(auto_now=True)),
                ('examen_recommande', models.CharField(blank=True, max_length=32, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
    ]
