# Generated by Django 4.1.13 on 2024-03-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ressources', '0001_initial'),
        ('Personnel_Service', '0003_alter_personnel_identifiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=9)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=32)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_analyse', models.CharField(max_length=32)),
                ('dure_analyse', models.DateTimeField()),
                ('prix_analyse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=128)),
                ('num_lit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ressources.lit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.service')),
            ],
        ),
        migrations.CreateModel(
            name='FactureSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(max_length=32)),
                ('montant', models.IntegerField()),
                ('date_facture', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='FactureProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_factureproduit', models.DateTimeField()),
                ('montant', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_examen', models.CharField(max_length=128)),
                ('date_examen', models.DateTimeField()),
                ('laborantain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.typeanalyse')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.CharField(max_length=128)),
                ('antecedant', models.CharField(max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poid', models.DecimalField(decimal_places=2, max_digits=2)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=2)),
                ('tension', models.IntegerField()),
                ('age', models.IntegerField()),
                ('taille', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plainte', models.CharField(max_length=128)),
                ('diagnostic', models.CharField(max_length=128)),
                ('prescription', models.CharField(max_length=128)),
                ('date_consultation', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
    ]
