# Generated by Django 5.0.6 on 2024-05-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='patient',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='full_name',
            field=models.CharField(default='sow', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(default=11, max_length=9),
            preserve_default=False,
        ),
    ]
