# Generated by Django 4.1.13 on 2024-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_patient_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profil_patient',
            field=models.ImageField(blank=True, editable=False, upload_to='profil_patient/'),
        ),
    ]
