# Generated by Django 4.1.13 on 2024-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_patient_profil_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profil_patient',
            field=models.ImageField(blank=True, upload_to='profil_patient/'),
        ),
    ]
