# Generated by Django 4.1.1 on 2024-03-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel_Service', '0005_delete_rendezvous'),
        ('Patients', '0004_alter_patient_profil_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField()),
                ('heure_rdv', models.TimeField()),
                ('sujet_rdv', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnel_Service.personnel')),
            ],
        ),
    ]
