# Generated by Django 4.1.1 on 2024-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_patient_is_active_patient_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
