# Generated by Django 4.1.1 on 2024-03-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_staff',
        ),
    ]
