# Generated by Django 4.1.1 on 2024-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0010_remove_rendezvous_status_rendezvous_status_rdv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date_rdv',
            field=models.DateField(),
        ),
    ]
