# Generated by Django 4.1.1 on 2024-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0012_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_enrgistrement',
            field=models.DateField(auto_now=True),
        ),
    ]
